### ISSUE TITLE
Jump to step Initiate code-server link doesn't work.

### ISSUE THREAD

**Issue by jkwmoore** [rcgsheffield/vscoderemote_sheffield_hpc#6]
Can you have a tweak of the README to get that working?

**Comment by jkwmoore** [comment]
Likewise for 
`
(see below for [Bessemer instructions](https://github.com/rcgsheffield/vscoderemote_sheffield_hpc###starting-vscode-remote-server-using-a-batch-job-on-bessmer))`

Should probably be:

`(see below for [Bessemer instructions](https://github.com/rcgsheffield/vscoderemote_sheffield_hpc#starting-vscode-remote-server-using-a-batch-job-on-bessmer))`

**Comment by Carldkennedy** [comment]
Fixed and merged. Thank you!
